[package]
name = "injector"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.126"
winreg = "0.10.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"
chrono = "0.4.19"

[dependencies.winapi]
version = "0.3.9"
features = [
    "memoryapi",
    "tlhelp32",
]